#
# curl -H'host: hello-app.clh.org' http://<IstioGwyControolerIP>:80
# expected result: round robin hello-app versions answer

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    field.cattle.io/projectId: p-q8w8l
    istio-injection: enabled
  name: hello-app
spec: {}

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  annotations:
  name: hello-app
  namespace: hello-app
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*/*.clh.org'
    port:
      name: http
      number: 80
      protocol: HTTP

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-app
  namespace: hello-app
spec:
  gateways:
  - hello-app
  hosts:
  - hello-app.clh.org
  http:
  - route:
    - destination:
        host: hello-app.hello-app.svc.cluster.local
        port:
          number: 8080
